---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:047719652562:task-definition/springproject1TD:3"
        LoadBalancerInfo:
          ContainerName: "spingproject1container"
          ContainerPort: 8080
