version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - yum install -y jq maven
      - echo Logging in to Amazon ECR...
      - export ACCOUNT_ID=047719652562
      - export REGION=us-east-1
      - export REPO_NAME=aws-ecs-docker
      - export IMAGE_TAG=latest
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

  build:
    commands:
      - echo Building the JAR file...
      - mvn clean install
      - echo Building the Docker image...
      - docker build -t $REPO_NAME:$IMAGE_TAG .
      - docker tag $REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"spingproject1containerr","imageUri":"%s.dkr.ecr.%s.amazonaws.com/%s:%s"}]' $ACCOUNT_ID $REGION $REPO_NAME $IMAGE_TAG > imagedefinitions.json
      - echo Writing appspec.yml...
      - |
        cat <<EOF > appspec.yml
        version: 0.0
        Resources:
          - TargetService:
              Type: AWS::ECS::Service
              Properties:
                TaskDefinition: 
                  Ref: TaskDefinition
                LoadBalancerInfo:
                  ContainerName: "sprinrajco"
                  ContainerPort: 8080
        EOF

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml
